#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -t git -t nvim -t zsh -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-git/gitconfig" "/home/pierrebeaucamp/.gitconfig"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/bundles.vim" "/home/pierrebeaucamp/.config/nvim/bundles.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/init.vim" "/home/pierrebeaucamp/.config/nvim/init.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/statusline.vim" "/home/pierrebeaucamp/.config/nvim/statusline.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-zsh/aliases" "/home/pierrebeaucamp/.aliases"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-zsh/exports" "/home/pierrebeaucamp/.exports"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-zsh/functions" "/home/pierrebeaucamp/.functions"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-zsh/zshrc" "/home/pierrebeaucamp/.zshrc"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/rcrc" "/home/pierrebeaucamp/.rcrc"
