#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -t git -t nvim -t fish -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=cp}
: ${LN:=ln}
: ${MKDIR:=mkdir}
: ${RM:=rm}
: ${DIRNAME:=dirname}
: ${XARGS:=xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-git/gitconfig" "/home/pierrebeaucamp/.gitconfig"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/autoload/plug.vim" "/home/pierrebeaucamp/.config/nvim/autoload/plug.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/bundles.vim" "/home/pierrebeaucamp/.config/nvim/bundles.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/init.vim" "/home/pierrebeaucamp/.config/nvim/init.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/config/nvim/statusline.vim" "/home/pierrebeaucamp/.config/nvim/statusline.vim"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-nvim/eslintrc" "/home/pierrebeaucamp/.eslintrc"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/conf.d/aliases.fish" "/home/pierrebeaucamp/.config/fish/conf.d/aliases.fish"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/conf.d/exports.fish" "/home/pierrebeaucamp/.config/fish/conf.d/exports.fish"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/conf.d/functions.fish" "/home/pierrebeaucamp/.config/fish/conf.d/functions.fish"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/config.fish" "/home/pierrebeaucamp/.config/fish/config.fish"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/fishfile" "/home/pierrebeaucamp/.config/fish/fishfile"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/tag-fish/config/fish/functions/fisher.fish" "/home/pierrebeaucamp/.config/fish/functions/fisher.fish"
handle_file_ln "/home/pierrebeaucamp/.dotfiles/rcrc" "/home/pierrebeaucamp/.rcrc"
