# Bundles
source $HOME/.antigen.zsh
antigen bundle command-not-found
antigen bundle rupa/z
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle trapd00r/zsh-syntax-highlighting-filetypes
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen apply

# Generic zsh settings
setopt NO_BG_NICE
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
setopt IGNORE_EOF

# History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_VERIFY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS

# Key mappings
bindkey -v
export KEYTIMEOUT=1
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char

# Prompt
VIM_PROMPT="❯"
PROMPT='%(?.%F{magenta}.%F{red})${VIM_PROMPT}%f '

function zle-line-init zle-keymap-select {
    zle || {
        print "error: pure_update_vim_prompt must be called when zle is active"
        return 1
    }
    VIM_PROMPT=${${KEYMAP/vicmd/❮}/(main|viins)/❯}
    zle .reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

# do 'ls' after 'cd'
auto-ls() {
    emulate -L zsh;
    # no aliases here
    ls -aFG
}
chpwd_functions=( auto-ls $chpwd_functions )

# Autocompletion
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'
zstyle ':completion:*' insert-tab pending
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
setopt complete_aliases

[[ -s "/home/pierrebeaucamp/.gvm/scripts/gvm" ]] && source "/home/pierrebeaucamp/.gvm/scripts/gvm"

export NVM_DIR="/home/pierrebeaucamp/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Load our dotfiles like ~/.bash_prompt, etc...
for file in ~/.{exports,aliases,functions,profile}; do
    [ -r "$file"  ] && source "$file"
done
unset file

# Source karma stuff
source "/mnt/c/Users/Pierre Beaucamp/Code/go/src/github.com/ilovetravel/karma-devops/scripts/local-env.sh"
